/*
 * =============================================================================
 * Copyright (c) 2008 Exaid. All rights reserved.
 * =============================================================================
 */

/*
 * TransferPanel.java
 *
 * Created on Feb 11, 2009, 8:14:01 PM
 */
package sfsui;

import javax.swing.JProgressBar;
import no.eirikb.sfs.client.LocalShare;
import no.eirikb.sfs.share.ShareFolder;

/**
 *
 * @author eirikb
 */
public class TransferPanel extends javax.swing.JPanel {

    private LocalShare localShare;
    private JProgressBar[] progressBars;

    /** Creates new form TransferPanel */
    public TransferPanel(LocalShare localShare, ShareFolder[] parts) {
        this.localShare = localShare;
        initComponents();
        progressBars = new JProgressBar[parts.length];
        for (int i = 0; i < parts.length; i++) {
            progressBars[i] = new JProgressBar(0, (int)parts[i].getSize());
            System.out.println(parts[i].getSize());
            transferPanel.add(progressBars[i]);
            transferPanel.updateUI();
        }
    }

    public void receiveStatus(int partNumber, long bytes) {
        progressBars[partNumber].setValue(progressBars[partNumber].getValue() + (int) bytes);
        System.out.println(progressBars[partNumber].getMaximum() + " - " + progressBars[partNumber].getValue());
        transferPanel.updateUI();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        transferPanel = new javax.swing.JPanel();

        setName("Form"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(sfsui.SFSUIApp.class).getContext().getResourceMap(TransferPanel.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        add(jLabel1, java.awt.BorderLayout.PAGE_START);

        transferPanel.setName("transferPanel"); // NOI18N
        transferPanel.setLayout(new java.awt.GridLayout());
        add(transferPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel transferPanel;
    // End of variables declaration//GEN-END:variables
}
