/*
 * ProgressBarTest.java
 *
 * Created on October 29, 2008, 8:51 AM
 */
package no.eirikb.sfs.client;

import java.awt.GridLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JProgressBar;

/**
 *
 * @author  eirikb
 */
public class ProgressBarTest extends javax.swing.JFrame {

    /** Creates new form ProgressBarTest */
    public ProgressBarTest() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 200, 200));

        jPanel1.setLayout(new java.awt.GridLayout());
        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    final int SIZE = 4;
    final int LENGTH = 1000;
    final int SLEEP = 100;
    final JProgressBar[] bars = new JProgressBar[SIZE];
    for (int i = 0; i < SIZE; i++) {
        bars[i] = new JProgressBar();
        bars[i].setMaximum((int) (Math.random() * LENGTH));
        bars[i].setVisible(true);
        jPanel1.add(bars[i]);
    }


    new Thread() {

        public void run() {

            for (int j = 0; j < LENGTH; j++) {
                for (int i = 0; i < SIZE; i++) {
                    bars[i].setValue(j);
                }
                try {
                    Thread.sleep(SLEEP);
                } catch (InterruptedException ex) {
                    Logger.getLogger(ProgressBarTest.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }.start();
    
}//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new  

              Runnable() {

                 public void run() {
                new ProgressBarTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
